version: "3"

services:
  # Development service
  dev:
    build:
      context: .
      target: deps
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  # Production service
  prod:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
